Storybook8 / pnpm (#50)

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,18 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
 
-bun fix
-bun lint-staged
+echo "Starting pre-commit hook"
+
+bun run lint
+if [ $? -ne 0 ]; then
+  echo "Linting failed"
+  exit 1
+fi
+
+bun run format
+if [ $? -ne 0 ]; then
+  echo "Formatting failed"
+  exit 1
+fi
+
+echo "Pre-commit hook succeeded"
